AWSTemplateFormatVersion: "2010-09-09"
Description: MLOps-Ethnicity-Prediction-Setup
Parameters: 
  UniqueID: 
    Type: String
    Default: yourinitials
    Description: Enter your initials in lower case as a unique identifier for components created 
    AllowedPattern: "^([a-z]|(d(?!d{0,2}.d{1,3}.d{1,3}.d{1,3})))([a-zd]|(.(?!(.|-)))|(-(?!.))){1,61}[a-zd.]$"

Resources:

            
  S3LambdaFunctionCode:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: BucketOwnerFullControl
      VersioningConfiguration: 
        Status: Enabled
      BucketName:
        Fn::Join:
          - ""
          - - "ethnicity-pred-lambda-code-"
            - !Ref UniqueID
            - "-"
            - !Select
             - 0
             - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"

  CodeCommitRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: "ethnicity-pred-repo"
      RepositoryDescription: "Ethnicity Prediction Code Commit Repository"

  SageMakerNotebookLifecycleConfig:
    Type: AWS::SageMaker::NotebookInstanceLifecycleConfig
    Properties: 
      NotebookInstanceLifecycleConfigName: "Ethnicity-Pred-Lifecycle-Config"
      OnCreate:
        - Content: 
            Fn::Base64: !Sub |
                #!/bin/bash
                set -e
                sudo -i -u ec2-user bash << EOF
                echo "Setup the code"
                git clone https://github.com/krishnamanchikalapudi/mlops-ethnicity-prediction.git
                pwd
                ls -la
                mkdir /home/ec2-user/SageMaker/mlops-ethnicity-prediction
                cp -R /home/ec2-user/mlops-ethnicity-prediction/* /home/ec2-user/SageMaker/mlops-ethnicity-prediction/
    DependsOn: CodeCommitRepo
 
  SageMakerNotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties: 
      DefaultCodeRepository: !GetAtt CodeCommitRepo.CloneUrlHttp
      InstanceType: ml.t3.medium
      LifecycleConfigName: "Ethnicity-Pred-Lifecycle-Config"
      NotebookInstanceName: 
        Fn::Join:
            - ""
            - - "Ethnicity-Prediction-Notebook-"
              - !Ref UniqueID
      RoleArn: !GetAtt [SageMakerNotebookInstanceRole, Arn]
      
  SageMakerNotebookInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: sagemaker.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
          - arn:aws:iam::aws:policy/AmazonS3FullAccess
          - arn:aws:iam::aws:policy/AWSCodeCommitFullAccess
          - arn:aws:iam::aws:policy/AWSDataPipeline_FullAccess
          - arn:aws:iam::aws:policy/AmazonAPIGatewayInvokeFullAccess
          - arn:aws:iam::aws:policy/AWSLambda_FullAccess
      RoleName: 
        Fn::Join:
           - ""
           - - "Ethnicity-Prediction-NotebookInstance-ServiceRole-"
             - !Ref UniqueID

Outputs:
      SageMakerNotebookInstance:
        Description: The ID of the SageMaker Notebook Instance
        Value: !Ref SageMakerNotebookInstance
      CodeCommitRepo:
        Description: The ID of the CodeCommit Repository
        Value: !Ref CodeCommitRepo 


